spring:
  application:
    name: api-gateway

  app:
    jwtSecret: d2lraV9zZWNyZXRfa2V5X2Zvcl9hcGlfZ2F0ZXdheV9hbmRfamlm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri:  http://order-service.microservices.local:8083
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service.microservices.local:8084
          predicates:
            - Path=/payments/**
        - id: restaurant-service
          uri: http://restaurant-service.microservices.local:8082
          predicates:
            - Path=/restaurants/**
        - id: delivery-service
          uri: http://delivery-service.microservices.local:8085
          predicates:
            - Path=/delivery/**
        - id: auth-service
          uri: http://auth-service.microservices.local:8081
          predicates:
            - Path=/auth/**
        - id: dlq-consumer-service
          uri: http://dlq-consumer.microservices.local:8086
          predicates:
            - Path=/dlq/**

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
